#! /bin/sh

# Startup stuff
sxhkd &
compton -b
./.config/polybar/crazylauncher.sh
feh --bg-scale ~/Pictures/train.jpg

# BSP Config Stuff
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          10
bspc config focused_border_color "#cccccc"
bspc config presel_feedback_color "#888888"

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false